# Generated by Django 5.0.3 on 2024-03-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='title',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
