# Generated by Django 5.0.3 on 2024-03-22 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 12, 14, 33, 85801, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
